/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExpenseCategory = IDL.Variant({
  'other' : IDL.Null,
  'fees' : IDL.Null,
  'groceries' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Role = IDL.Variant({ 'child' : IDL.Null, 'parent' : IDL.Null });
export const FamilyInvitation = IDL.Record({
  'created' : IDL.Int,
  'token' : IDL.Text,
  'expires' : IDL.Int,
  'parentPrincipal' : IDL.Principal,
  'childPrincipal' : IDL.Principal,
  'isValid' : IDL.Bool,
});
export const FamilyMember = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
});
export const ExpenseEntry = IDL.Record({
  'timestamp' : IDL.Int,
  'category' : ExpenseCategory,
  'amount' : IDL.Nat,
});
export const Expenses = IDL.Record({
  'totalOther' : IDL.Nat,
  'totalGroceries' : IDL.Nat,
  'totalFees' : IDL.Nat,
  'entries' : IDL.Vec(ExpenseEntry),
});
export const Location = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
  'timestamp' : IDL.Int,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'role' : IDL.Opt(Role),
  'lastUpdate' : IDL.Int,
  'children' : IDL.Vec(FamilyMember),
  'totalExpenses' : Expenses,
  'parents' : IDL.Vec(FamilyMember),
  'location' : IDL.Opt(Location),
  'avatar' : IDL.Opt(ExternalBlob),
});
export const MessageType = IDL.Variant({
  'text' : IDL.Null,
  'socialMediaLink' : IDL.Null,
  'groceryList' : IDL.Null,
});
export const ChatType = IDL.Variant({
  'privateChat' : IDL.Null,
  'group' : IDL.Null,
});
export const Message = IDL.Record({
  'socialMediaUrl' : IDL.Opt(IDL.Text),
  'text' : IDL.Text,
  'author' : IDL.Principal,
  'messageType' : MessageType,
  'groceryItems' : IDL.Opt(IDL.Vec(IDL.Text)),
  'timestamp' : IDL.Int,
  'chatType' : ChatType,
  'recipientId' : IDL.Opt(IDL.Principal),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addChild' : IDL.Func([IDL.Text, IDL.Principal], [], []),
  'addExpense' : IDL.Func([ExpenseCategory, IDL.Nat], [], []),
  'addParent' : IDL.Func([IDL.Text, IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createFamilyInvitationToken' : IDL.Func(
      [IDL.Principal, IDL.Nat],
      [IDL.Text],
      [],
    ),
  'createProfile' : IDL.Func([IDL.Text, Role], [], []),
  'deleteAccount' : IDL.Func([], [], []),
  'getActiveFamilyInvitations' : IDL.Func(
      [],
      [IDL.Vec(FamilyInvitation)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExpenseSummary' : IDL.Func([], [Expenses], ['query']),
  'getMessageHistory' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeChild' : IDL.Func([IDL.Principal], [], []),
  'removeParent' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func(
      [
        IDL.Text,
        MessageType,
        IDL.Opt(IDL.Vec(IDL.Text)),
        IDL.Opt(IDL.Text),
        ChatType,
        IDL.Opt(IDL.Principal),
      ],
      [],
      [],
    ),
  'updateUserProfile' : IDL.Func([UserProfile], [], []),
  'validateFamilyInvitationToken' : IDL.Func(
      [IDL.Text, IDL.Principal],
      [IDL.Principal],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExpenseCategory = IDL.Variant({
    'other' : IDL.Null,
    'fees' : IDL.Null,
    'groceries' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Role = IDL.Variant({ 'child' : IDL.Null, 'parent' : IDL.Null });
  const FamilyInvitation = IDL.Record({
    'created' : IDL.Int,
    'token' : IDL.Text,
    'expires' : IDL.Int,
    'parentPrincipal' : IDL.Principal,
    'childPrincipal' : IDL.Principal,
    'isValid' : IDL.Bool,
  });
  const FamilyMember = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
  });
  const ExpenseEntry = IDL.Record({
    'timestamp' : IDL.Int,
    'category' : ExpenseCategory,
    'amount' : IDL.Nat,
  });
  const Expenses = IDL.Record({
    'totalOther' : IDL.Nat,
    'totalGroceries' : IDL.Nat,
    'totalFees' : IDL.Nat,
    'entries' : IDL.Vec(ExpenseEntry),
  });
  const Location = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
    'timestamp' : IDL.Int,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'role' : IDL.Opt(Role),
    'lastUpdate' : IDL.Int,
    'children' : IDL.Vec(FamilyMember),
    'totalExpenses' : Expenses,
    'parents' : IDL.Vec(FamilyMember),
    'location' : IDL.Opt(Location),
    'avatar' : IDL.Opt(ExternalBlob),
  });
  const MessageType = IDL.Variant({
    'text' : IDL.Null,
    'socialMediaLink' : IDL.Null,
    'groceryList' : IDL.Null,
  });
  const ChatType = IDL.Variant({
    'privateChat' : IDL.Null,
    'group' : IDL.Null,
  });
  const Message = IDL.Record({
    'socialMediaUrl' : IDL.Opt(IDL.Text),
    'text' : IDL.Text,
    'author' : IDL.Principal,
    'messageType' : MessageType,
    'groceryItems' : IDL.Opt(IDL.Vec(IDL.Text)),
    'timestamp' : IDL.Int,
    'chatType' : ChatType,
    'recipientId' : IDL.Opt(IDL.Principal),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addChild' : IDL.Func([IDL.Text, IDL.Principal], [], []),
    'addExpense' : IDL.Func([ExpenseCategory, IDL.Nat], [], []),
    'addParent' : IDL.Func([IDL.Text, IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createFamilyInvitationToken' : IDL.Func(
        [IDL.Principal, IDL.Nat],
        [IDL.Text],
        [],
      ),
    'createProfile' : IDL.Func([IDL.Text, Role], [], []),
    'deleteAccount' : IDL.Func([], [], []),
    'getActiveFamilyInvitations' : IDL.Func(
        [],
        [IDL.Vec(FamilyInvitation)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExpenseSummary' : IDL.Func([], [Expenses], ['query']),
    'getMessageHistory' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeChild' : IDL.Func([IDL.Principal], [], []),
    'removeParent' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func(
        [
          IDL.Text,
          MessageType,
          IDL.Opt(IDL.Vec(IDL.Text)),
          IDL.Opt(IDL.Text),
          ChatType,
          IDL.Opt(IDL.Principal),
        ],
        [],
        [],
      ),
    'updateUserProfile' : IDL.Func([UserProfile], [], []),
    'validateFamilyInvitationToken' : IDL.Func(
        [IDL.Text, IDL.Principal],
        [IDL.Principal],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };