/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ChatType = { 'privateChat' : null } |
  { 'group' : null };
export type ExpenseCategory = { 'other' : null } |
  { 'fees' : null } |
  { 'groceries' : null };
export interface ExpenseEntry {
  'timestamp' : bigint,
  'category' : ExpenseCategory,
  'amount' : bigint,
}
export interface Expenses {
  'totalOther' : bigint,
  'totalGroceries' : bigint,
  'totalFees' : bigint,
  'entries' : Array<ExpenseEntry>,
}
export type ExternalBlob = Uint8Array;
export interface FamilyInvitation {
  'created' : bigint,
  'token' : string,
  'expires' : bigint,
  'parentPrincipal' : Principal,
  'childPrincipal' : Principal,
  'isValid' : boolean,
}
export interface FamilyMember { 'principal' : Principal, 'name' : string }
export interface Location {
  'latitude' : number,
  'longitude' : number,
  'timestamp' : bigint,
}
export interface Message {
  'socialMediaUrl' : [] | [string],
  'text' : string,
  'author' : Principal,
  'messageType' : MessageType,
  'groceryItems' : [] | [Array<string>],
  'timestamp' : bigint,
  'chatType' : ChatType,
  'recipientId' : [] | [Principal],
}
export type MessageType = { 'text' : null } |
  { 'socialMediaLink' : null } |
  { 'groceryList' : null };
export interface PermissionRequest {
  'id' : string,
  'child' : Principal,
  'granted' : boolean,
  'timestamp' : bigint,
  'requestType' : PermissionType,
  'parent' : FamilyMember,
  'reason' : string,
}
export type PermissionType = { 'goOut' : null } |
  { 'playGames' : null } |
  { 'watchYouTube' : null };
export type Role = { 'child' : null } |
  { 'parent' : null };
export interface UserProfile {
  'aiRemedyEnabled' : boolean,
  'displayName' : string,
  'role' : [] | [Role],
  'lastUpdate' : bigint,
  'children' : Array<FamilyMember>,
  'totalExpenses' : Expenses,
  'parents' : Array<FamilyMember>,
  'location' : [] | [Location],
  'avatar' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addChild' : ActorMethod<[string, Principal], undefined>,
  'addExpense' : ActorMethod<[ExpenseCategory, bigint], undefined>,
  'addParent' : ActorMethod<[string, Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createFamilyInvitationToken' : ActorMethod<[Principal, bigint], string>,
  'createPermissionRequest' : ActorMethod<
    [Principal, PermissionType, string],
    string
  >,
  'createProfile' : ActorMethod<[string, Role], undefined>,
  'getAIRemedyEnabled' : ActorMethod<[], boolean>,
  'getActiveFamilyInvitations' : ActorMethod<[], Array<FamilyInvitation>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExpenseSummary' : ActorMethod<[], Expenses>,
  'getFightsCreated' : ActorMethod<[], bigint>,
  'getFightsSolved' : ActorMethod<[], bigint>,
  'getMessageHistory' : ActorMethod<[], Array<Message>>,
  'getPermissionRequests' : ActorMethod<[], Array<PermissionRequest>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'incrementFightsCreated' : ActorMethod<[], undefined>,
  'incrementFightsSolved' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeChild' : ActorMethod<[Principal], undefined>,
  'removeParent' : ActorMethod<[Principal], undefined>,
  'respondToPermissionRequest' : ActorMethod<[string, boolean], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<
    [
      string,
      MessageType,
      [] | [Array<string>],
      [] | [string],
      ChatType,
      [] | [Principal],
    ],
    undefined
  >,
  'setAIRemedyEnabled' : ActorMethod<[boolean], undefined>,
  'updateUserProfile' : ActorMethod<[UserProfile], undefined>,
  'validateFamilyInvitationToken' : ActorMethod<[string, Principal], Principal>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];