/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Location {
    latitude: number;
    longitude: number;
    timestamp: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface FamilyMember {
    principal: Principal;
    name: string;
}
export interface PermissionRequest {
    id: string;
    child: Principal;
    granted: boolean;
    timestamp: bigint;
    requestType: PermissionType;
    parent: FamilyMember;
    reason: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface FamilyInvitation {
    created: bigint;
    token: string;
    expires: bigint;
    parentPrincipal: Principal;
    childPrincipal: Principal;
    isValid: boolean;
}
export interface Message {
    socialMediaUrl?: string;
    text: string;
    author: Principal;
    messageType: MessageType;
    groceryItems?: Array<string>;
    timestamp: bigint;
    chatType: ChatType;
    recipientId?: Principal;
}
export interface Expenses {
    totalOther: bigint;
    totalGroceries: bigint;
    totalFees: bigint;
    entries: Array<ExpenseEntry>;
}
export interface ExpenseEntry {
    timestamp: bigint;
    category: ExpenseCategory;
    amount: bigint;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    aiRemedyEnabled: boolean;
    displayName: string;
    role?: Role;
    lastUpdate: bigint;
    children: Array<FamilyMember>;
    totalExpenses: Expenses;
    parents: Array<FamilyMember>;
    location?: Location;
    avatar?: ExternalBlob;
}
export enum ChatType {
    privateChat = "privateChat",
    group = "group"
}
export enum ExpenseCategory {
    other = "other",
    fees = "fees",
    groceries = "groceries"
}
export enum MessageType {
    text = "text",
    socialMediaLink = "socialMediaLink",
    groceryList = "groceryList"
}
export enum PermissionType {
    goOut = "goOut",
    playGames = "playGames",
    watchYouTube = "watchYouTube"
}
export enum Role {
    child = "child",
    parent = "parent"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addChild(childName: string, childPrincipal: Principal): Promise<void>;
    addExpense(category: ExpenseCategory, amount: bigint): Promise<void>;
    addParent(parentName: string, parentPrincipal: Principal): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createFamilyInvitationToken(child: Principal, validationTimeHours: bigint): Promise<string>;
    createPermissionRequest(parentPrincipal: Principal, requestType: PermissionType, reason: string): Promise<string>;
    createProfile(displayName: string, role: Role): Promise<void>;
    getAIRemedyEnabled(): Promise<boolean>;
    getActiveFamilyInvitations(): Promise<Array<FamilyInvitation>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getExpenseSummary(): Promise<Expenses>;
    getFightsCreated(): Promise<bigint>;
    getFightsSolved(): Promise<bigint>;
    getMessageHistory(): Promise<Array<Message>>;
    getPermissionRequests(): Promise<Array<PermissionRequest>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    incrementFightsCreated(): Promise<void>;
    incrementFightsSolved(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    removeChild(childPrincipal: Principal): Promise<void>;
    removeParent(parentPrincipal: Principal): Promise<void>;
    respondToPermissionRequest(requestId: string, granted: boolean): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendMessage(text: string, messageType: MessageType, groceryItems: Array<string> | null, socialMediaUrl: string | null, chatType: ChatType, recipientId: Principal | null): Promise<void>;
    setAIRemedyEnabled(enabled: boolean): Promise<void>;
    updateUserProfile(profile: UserProfile): Promise<void>;
    validateFamilyInvitationToken(token: string, child: Principal): Promise<Principal>;
}
import type { ChatType as _ChatType, ExpenseCategory as _ExpenseCategory, ExpenseEntry as _ExpenseEntry, Expenses as _Expenses, ExternalBlob as _ExternalBlob, FamilyMember as _FamilyMember, Location as _Location, Message as _Message, MessageType as _MessageType, PermissionRequest as _PermissionRequest, PermissionType as _PermissionType, Role as _Role, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addChild(arg0: string, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addChild(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addChild(arg0, arg1);
            return result;
        }
    }
    async addExpense(arg0: ExpenseCategory, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addExpense(to_candid_ExpenseCategory_n8(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExpense(to_candid_ExpenseCategory_n8(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async addParent(arg0: string, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addParent(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addParent(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createFamilyInvitationToken(arg0: Principal, arg1: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createFamilyInvitationToken(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFamilyInvitationToken(arg0, arg1);
            return result;
        }
    }
    async createPermissionRequest(arg0: Principal, arg1: PermissionType, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createPermissionRequest(arg0, to_candid_PermissionType_n12(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPermissionRequest(arg0, to_candid_PermissionType_n12(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async createProfile(arg0: string, arg1: Role): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createProfile(arg0, to_candid_Role_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProfile(arg0, to_candid_Role_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAIRemedyEnabled(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getAIRemedyEnabled();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAIRemedyEnabled();
            return result;
        }
    }
    async getActiveFamilyInvitations(): Promise<Array<FamilyInvitation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveFamilyInvitations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveFamilyInvitations();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExpenseSummary(): Promise<Expenses> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpenseSummary();
                return from_candid_Expenses_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpenseSummary();
            return from_candid_Expenses_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFightsCreated(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getFightsCreated();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFightsCreated();
            return result;
        }
    }
    async getFightsSolved(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getFightsSolved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFightsSolved();
            return result;
        }
    }
    async getMessageHistory(): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessageHistory();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessageHistory();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPermissionRequests(): Promise<Array<PermissionRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPermissionRequests();
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPermissionRequests();
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async incrementFightsCreated(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementFightsCreated();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementFightsCreated();
            return result;
        }
    }
    async incrementFightsSolved(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementFightsSolved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementFightsSolved();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async removeChild(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeChild(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeChild(arg0);
            return result;
        }
    }
    async removeParent(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeParent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeParent(arg0);
            return result;
        }
    }
    async respondToPermissionRequest(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.respondToPermissionRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.respondToPermissionRequest(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n49(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n49(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async sendMessage(arg0: string, arg1: MessageType, arg2: Array<string> | null, arg3: string | null, arg4: ChatType, arg5: Principal | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, to_candid_MessageType_n57(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n59(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n60(this._uploadFile, this._downloadFile, arg3), to_candid_ChatType_n61(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n63(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, to_candid_MessageType_n57(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n59(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n60(this._uploadFile, this._downloadFile, arg3), to_candid_ChatType_n61(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n63(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async setAIRemedyEnabled(arg0: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAIRemedyEnabled(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAIRemedyEnabled(arg0);
            return result;
        }
    }
    async updateUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserProfile(await to_candid_UserProfile_n49(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserProfile(await to_candid_UserProfile_n49(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async validateFamilyInvitationToken(arg0: string, arg1: Principal): Promise<Principal> {
        if (this.processError) {
            try {
                const result = await this.actor.validateFamilyInvitationToken(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateFamilyInvitationToken(arg0, arg1);
            return result;
        }
    }
}
function from_candid_ChatType_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChatType): ChatType {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_ExpenseCategory_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExpenseCategory): ExpenseCategory {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_ExpenseEntry_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExpenseEntry): ExpenseEntry {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Expenses_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Expenses): Expenses {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_MessageType_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MessageType): MessageType {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_Message_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Message): Message {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_PermissionRequest_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PermissionRequest): PermissionRequest {
    return from_candid_record_n46(_uploadFile, _downloadFile, value);
}
function from_candid_PermissionType_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PermissionType): PermissionType {
    return from_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Role]): Role | null {
    return value.length === 0 ? null : from_candid_Role_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Location]): Location | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n31(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<string>]): Array<string> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    aiRemedyEnabled: boolean;
    displayName: string;
    role: [] | [_Role];
    lastUpdate: bigint;
    children: Array<_FamilyMember>;
    totalExpenses: _Expenses;
    parents: Array<_FamilyMember>;
    location: [] | [_Location];
    avatar: [] | [_ExternalBlob];
}): Promise<{
    aiRemedyEnabled: boolean;
    displayName: string;
    role?: Role;
    lastUpdate: bigint;
    children: Array<FamilyMember>;
    totalExpenses: Expenses;
    parents: Array<FamilyMember>;
    location?: Location;
    avatar?: ExternalBlob;
}> {
    return {
        aiRemedyEnabled: value.aiRemedyEnabled,
        displayName: value.displayName,
        role: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.role)),
        lastUpdate: value.lastUpdate,
        children: value.children,
        totalExpenses: from_candid_Expenses_n22(_uploadFile, _downloadFile, value.totalExpenses),
        parents: value.parents,
        location: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.location)),
        avatar: record_opt_to_undefined(await from_candid_opt_n30(_uploadFile, _downloadFile, value.avatar))
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalOther: bigint;
    totalGroceries: bigint;
    totalFees: bigint;
    entries: Array<_ExpenseEntry>;
}): {
    totalOther: bigint;
    totalGroceries: bigint;
    totalFees: bigint;
    entries: Array<ExpenseEntry>;
} {
    return {
        totalOther: value.totalOther,
        totalGroceries: value.totalGroceries,
        totalFees: value.totalFees,
        entries: from_candid_vec_n24(_uploadFile, _downloadFile, value.entries)
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    timestamp: bigint;
    category: _ExpenseCategory;
    amount: bigint;
}): {
    timestamp: bigint;
    category: ExpenseCategory;
    amount: bigint;
} {
    return {
        timestamp: value.timestamp,
        category: from_candid_ExpenseCategory_n27(_uploadFile, _downloadFile, value.category),
        amount: value.amount
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    socialMediaUrl: [] | [string];
    text: string;
    author: Principal;
    messageType: _MessageType;
    groceryItems: [] | [Array<string>];
    timestamp: bigint;
    chatType: _ChatType;
    recipientId: [] | [Principal];
}): {
    socialMediaUrl?: string;
    text: string;
    author: Principal;
    messageType: MessageType;
    groceryItems?: Array<string>;
    timestamp: bigint;
    chatType: ChatType;
    recipientId?: Principal;
} {
    return {
        socialMediaUrl: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.socialMediaUrl)),
        text: value.text,
        author: value.author,
        messageType: from_candid_MessageType_n38(_uploadFile, _downloadFile, value.messageType),
        groceryItems: record_opt_to_undefined(from_candid_opt_n40(_uploadFile, _downloadFile, value.groceryItems)),
        timestamp: value.timestamp,
        chatType: from_candid_ChatType_n41(_uploadFile, _downloadFile, value.chatType),
        recipientId: record_opt_to_undefined(from_candid_opt_n43(_uploadFile, _downloadFile, value.recipientId))
    };
}
function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    child: Principal;
    granted: boolean;
    timestamp: bigint;
    requestType: _PermissionType;
    parent: _FamilyMember;
    reason: string;
}): {
    id: string;
    child: Principal;
    granted: boolean;
    timestamp: bigint;
    requestType: PermissionType;
    parent: FamilyMember;
    reason: string;
} {
    return {
        id: value.id,
        child: value.child,
        granted: value.granted,
        timestamp: value.timestamp,
        requestType: from_candid_PermissionType_n47(_uploadFile, _downloadFile, value.requestType),
        parent: value.parent,
        reason: value.reason
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    child: null;
} | {
    parent: null;
}): Role {
    return "child" in value ? Role.child : "parent" in value ? Role.parent : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    fees: null;
} | {
    groceries: null;
}): ExpenseCategory {
    return "other" in value ? ExpenseCategory.other : "fees" in value ? ExpenseCategory.fees : "groceries" in value ? ExpenseCategory.groceries : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    text: null;
} | {
    socialMediaLink: null;
} | {
    groceryList: null;
}): MessageType {
    return "text" in value ? MessageType.text : "socialMediaLink" in value ? MessageType.socialMediaLink : "groceryList" in value ? MessageType.groceryList : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    privateChat: null;
} | {
    group: null;
}): ChatType {
    return "privateChat" in value ? ChatType.privateChat : "group" in value ? ChatType.group : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    goOut: null;
} | {
    playGames: null;
} | {
    watchYouTube: null;
}): PermissionType {
    return "goOut" in value ? PermissionType.goOut : "playGames" in value ? PermissionType.playGames : "watchYouTube" in value ? PermissionType.watchYouTube : value;
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExpenseEntry>): Array<ExpenseEntry> {
    return value.map((x)=>from_candid_ExpenseEntry_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Message>): Array<Message> {
    return value.map((x)=>from_candid_Message_n35(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PermissionRequest>): Array<PermissionRequest> {
    return value.map((x)=>from_candid_PermissionRequest_n45(_uploadFile, _downloadFile, x));
}
function to_candid_ChatType_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChatType): _ChatType {
    return to_candid_variant_n62(_uploadFile, _downloadFile, value);
}
function to_candid_ExpenseCategory_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExpenseCategory): _ExpenseCategory {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_ExpenseEntry_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExpenseEntry): _ExpenseEntry {
    return to_candid_record_n55(_uploadFile, _downloadFile, value);
}
function to_candid_Expenses_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Expenses): _Expenses {
    return to_candid_record_n52(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_MessageType_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MessageType): _MessageType {
    return to_candid_variant_n58(_uploadFile, _downloadFile, value);
}
function to_candid_PermissionType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PermissionType): _PermissionType {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
async function to_candid_UserProfile_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): Promise<_UserProfile> {
    return await to_candid_record_n50(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<string> | null): [] | [Array<string>] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Principal | null): [] | [Principal] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    aiRemedyEnabled: boolean;
    displayName: string;
    role?: Role;
    lastUpdate: bigint;
    children: Array<FamilyMember>;
    totalExpenses: Expenses;
    parents: Array<FamilyMember>;
    location?: Location;
    avatar?: ExternalBlob;
}): Promise<{
    aiRemedyEnabled: boolean;
    displayName: string;
    role: [] | [_Role];
    lastUpdate: bigint;
    children: Array<_FamilyMember>;
    totalExpenses: _Expenses;
    parents: Array<_FamilyMember>;
    location: [] | [_Location];
    avatar: [] | [_ExternalBlob];
}> {
    return {
        aiRemedyEnabled: value.aiRemedyEnabled,
        displayName: value.displayName,
        role: value.role ? candid_some(to_candid_Role_n14(_uploadFile, _downloadFile, value.role)) : candid_none(),
        lastUpdate: value.lastUpdate,
        children: value.children,
        totalExpenses: to_candid_Expenses_n51(_uploadFile, _downloadFile, value.totalExpenses),
        parents: value.parents,
        location: value.location ? candid_some(value.location) : candid_none(),
        avatar: value.avatar ? candid_some(await to_candid_ExternalBlob_n56(_uploadFile, _downloadFile, value.avatar)) : candid_none()
    };
}
function to_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalOther: bigint;
    totalGroceries: bigint;
    totalFees: bigint;
    entries: Array<ExpenseEntry>;
}): {
    totalOther: bigint;
    totalGroceries: bigint;
    totalFees: bigint;
    entries: Array<_ExpenseEntry>;
} {
    return {
        totalOther: value.totalOther,
        totalGroceries: value.totalGroceries,
        totalFees: value.totalFees,
        entries: to_candid_vec_n53(_uploadFile, _downloadFile, value.entries)
    };
}
function to_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    timestamp: bigint;
    category: ExpenseCategory;
    amount: bigint;
}): {
    timestamp: bigint;
    category: _ExpenseCategory;
    amount: bigint;
} {
    return {
        timestamp: value.timestamp,
        category: to_candid_ExpenseCategory_n8(_uploadFile, _downloadFile, value.category),
        amount: value.amount
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PermissionType): {
    goOut: null;
} | {
    playGames: null;
} | {
    watchYouTube: null;
} {
    return value == PermissionType.goOut ? {
        goOut: null
    } : value == PermissionType.playGames ? {
        playGames: null
    } : value == PermissionType.watchYouTube ? {
        watchYouTube: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    child: null;
} | {
    parent: null;
} {
    return value == Role.child ? {
        child: null
    } : value == Role.parent ? {
        parent: null
    } : value;
}
function to_candid_variant_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MessageType): {
    text: null;
} | {
    socialMediaLink: null;
} | {
    groceryList: null;
} {
    return value == MessageType.text ? {
        text: null
    } : value == MessageType.socialMediaLink ? {
        socialMediaLink: null
    } : value == MessageType.groceryList ? {
        groceryList: null
    } : value;
}
function to_candid_variant_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChatType): {
    privateChat: null;
} | {
    group: null;
} {
    return value == ChatType.privateChat ? {
        privateChat: null
    } : value == ChatType.group ? {
        group: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExpenseCategory): {
    other: null;
} | {
    fees: null;
} | {
    groceries: null;
} {
    return value == ExpenseCategory.other ? {
        other: null
    } : value == ExpenseCategory.fees ? {
        fees: null
    } : value == ExpenseCategory.groceries ? {
        groceries: null
    } : value;
}
function to_candid_vec_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExpenseEntry>): Array<_ExpenseEntry> {
    return value.map((x)=>to_candid_ExpenseEntry_n54(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
